sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t egorovforjob/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true egorovforjob/react-test npm test

after_success:
  - docker build -t egorovforjob/test-client ./client
  - docker build -t egorovforjob/test-nginx ./nginx
  - docker build -t egorovforjob/test-server ./server
  - docker build -t egorovforjob/test-worker ./worker
  # Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker hub
  - docker push egorovforjob/test-client
  - docker push egorovforjob/test-nginx
  - docker push egorovforjob/test-server
  - docker push egorovforjob/test-worker

